{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "notification.fullname" . }}-metrics
  labels:
    {{- include "notification.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      name: http-metrics
  selector:
    {{- include "notification.selectorLabels" . | nindent 4 }}
{{- end }}