apiVersion: v2
name: notification-service
description: A Helm chart for deploying notification to Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

dependencies:
  - name: postgresql
    #        https://app-catalog.vmware.com/bitnami/releases/a5f09427-0f05-450f-b416-6d6824a4748a
    version: "18.1.10"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: postgresql.enabled
